Add file search utilites
ShokoAnime/Shoko-WebUI pull request #732
Opened 2023-12-24 11:01 UTC by duehoa1211

Link to #731

2023-12-25 20:30 UTC, ElementalCrisis commented
Looking good! Just a couple issues. 

1. Search doesn't seem to work. if I type in "One" I get no results. 
https://github.com/ShokoAnime/Shoko-WebUI/assets/9443295/0e835737-327c-4211-95b0-fcc4aab06124

2. Selected Files bleed through the header when scrolling.
![image](https://github.com/ShokoAnime/Shoko-WebUI/assets/9443295/a9ce1cd6-c013-45c9-bb46-b2c9f8f03d87)

There are some issues with the selected panel but that's more UI issues I can play around with later.

2023-12-26 07:52 UTC, duehoa1211 commented
> Looking good! Just a couple issues.
> 
> 1. Search doesn't seem to work. if I type in "One" I get no results when One Piece files should appear.
> 2. Selected Files bleed through the header when scrolling.
> 
> There are some issues with the selected panel but that's more UI issues I can play around with later.

I have fixed 
> 2. Selected Files bleed through the header when scrolling.the selected files bleed

but for the
> 1. Search doesn't seem to work. if I type in "One" I get no results when One Piece files should appear.

i think this one is back-end problem since the endpoint has changed.

2023-12-26 07:54 UTC, harshithmohan commented
Yeah... Someone reported it wasn't working in the unrecog util also.

Sent with Shortwave <https://www.shortwave.com?utm_medium=email&utm_content=signature&utm_source=Z2hhcnNoaXRobW9oYW5AZ21haWwuY29t>

On Tue Dec 26, 2023, 07:53 AM GMT, duehoa1211 ***@***.***> wrote:
>> Looking good! Just a couple issues.
>> 1. Search doesn't seem to work. if I type in "One" I get no results when One Piece files should appear.
>> 2. Selected Files bleed through the header when scrolling.
>> There are some issues with the selected panel but that's more UI issues I can play around with later.
> I have fixed
>> 1. Selected Files bleed through the header when scrolling.the selected files bleed
> but for the
>> 1. Search doesn't seem to work. if I type in "One" I get no results when One Piece files should appear.
> i think this one is back-end problem since the endpoint has changed.
> —
> Reply to this email directly, view it on GitHub <https://github.com/ShokoAnime/Shoko-WebUI/pull/732#issuecomment-1869341193>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AGGOKQXQYBKRPX4TRDQVXHDYLJ65ZAVCNFSM6AAAAABBBOM3LSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQNRZGM2DCMJZGM>.
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

2023-12-27 09:56 UTC, harshithmohan requested changes

2023-12-27 09:56 UTC, harshithmohan commented on src/core/react-query/episode/queries.ts
> +    queryKey: ['episode', 'single', episodeId],
```suggestion
    queryKey: ['episode', 'anidb', episodeId],
```

2023-12-27 09:56 UTC, harshithmohan commented on src/pages/utilities/FileSearch.tsx
> +  const seriesShokoId = useMemo(() => get(file, 'SeriesIDs.0.SeriesID.ID', 0), [file]);
```suggestion
  const seriesShokoId = file?.SeriesIDs?.[0].SeriesID.ID;
```
Memoization is costly if we are only accessing data from an object.

2023-12-27 09:56 UTC, harshithmohan commented on src/pages/utilities/FileSearch.tsx
> +  );
```suggestion
  const seriesAnidbId = file?.SeriesIDs?.[0].SeriesID.AniDB;
  const episodeId = file?.SeriesIDs?.[0].EpisodeIDs[0].ID;
  const { data: seriesInfo } = useSeriesAniDBQuery(seriesAnidbId!, !!seriesAnidbId);
  const { data: episodeInfo } = useEpisodeAniDBQuery(episodeId!, !!episodeId);
```

2023-12-27 09:56 UTC, harshithmohan commented on src/pages/utilities/FileSearch.tsx
> +  );
More readable and less duplicate code

2023-12-27 09:56 UTC, harshithmohan commented on src/pages/utilities/FileSearch.tsx
> +  );
Also, need to change the type of `EpisodeIDs` to `EpisodeIDsType[]` in `XRefsType`. It seems to be wrong
![image](https://github.com/ShokoAnime/Shoko-WebUI/assets/26010946/cb106876-d9f8-47f2-b1ea-1afab4c63535)

2023-12-27 09:56 UTC, harshithmohan commented on src/pages/utilities/FileSearch.tsx
> +  );
You can just pass `staticColumns` to the `UtilitiesTable` if you aren't going to add/remove anything. This is not needed

2023-12-27 09:56 UTC, harshithmohan commented on src/pages/utilities/FileSearch.tsx
> +  const renderTotalFiles = () => (
We already have this as a component. Use that. `ItemCount.tsx`

2023-12-27 09:56 UTC, harshithmohan commented on src/pages/utilities/FileSearch.tsx
> +  const renderMetadata = useMemo(() => {
This can be separated into a component

2023-12-27 09:56 UTC, harshithmohan commented on src/pages/utilities/FileSearch.tsx
> +          {(fileCount ?? 0) > 0
```suggestion
          {fileCount > 0
```
`fileCount` is always defined

2023-12-27 09:56 UTC, harshithmohan commented
https://github.com/ShokoAnime/Shoko-WebUI/assets/26010946/8b2f1675-8945-4f6a-a4c0-b09b5826409d

The scroll container changes when a file is selected 🤔

2023-12-27 09:57 UTC, harshithmohan commented
![image](https://github.com/ShokoAnime/Shoko-WebUI/assets/26010946/01b5300c-5aab-4131-be0e-6aa87b346edd)
File location is going out of the window

2023-12-28 17:54 UTC, harshithmohan commented
![image](https://github.com/ShokoAnime/Shoko-WebUI/assets/26010946/0e28214b-c615-4a68-971b-2da05e174171)
Don't show this button if the anidb file id is not available. It's pointing to `https://anidb.net/file/undefined`

2023-12-28 17:59 UTC, harshithmohan commented
`src/components/Utilities/Common/ItemCount.tsx`
This file can just be in `src/components/Utilities/`
We don't need a "common" folder. Everything in the "Utilities" folder will be common

2023-12-28 18:00 UTC, harshithmohan requested changes

2023-12-29 06:35 UTC, harshithmohan approved these changes

2023-12-29 06:37 UTC, merged