Mitigating responsive in web
ShokoAnime/Shoko-WebUI pull request #752
Opened 2024-01-04 09:54 UTC by duehoa1211

2024-01-06 13:37 UTC, duehoa1211 commented
Link to #745

2024-01-06 14:05 UTC, hidden4003 approved these changes

2024-01-06 20:08 UTC, ElementalCrisis commented
Your changes created new issues for the options bar at lower res now. 

![image](https://github.com/ShokoAnime/Shoko-WebUI/assets/9443295/7279aa74-afd4-403e-a86c-d511730155c2)
![image](https://github.com/ShokoAnime/Shoko-WebUI/assets/9443295/4ef8ecff-13d6-4699-a7ad-c18799144b1f)
![image](https://github.com/ShokoAnime/Shoko-WebUI/assets/9443295/e22dac62-db3b-420b-9add-946905305108)

Review the mockups in Figma (check Components page) as at 1280 and below, the search bar is always shown and takes up the entire width.

The button and padding styling has been changed as well. 

Correct
![image](https://github.com/ShokoAnime/Shoko-WebUI/assets/9443295/a533257a-a87c-467b-a43d-179f0ab78ab5)

Your Version
![image](https://github.com/ShokoAnime/Shoko-WebUI/assets/9443295/902c06cc-ab8a-47e4-a814-1d085157b775)

2024-01-06 20:20 UTC, ElementalCrisis commented
Here's an example when the options bar still fits at a lower browser res.
https://github.com/ShokoAnime/Shoko-WebUI/assets/9443295/4b551811-17bc-43b0-9e6f-fbeadb55cb7c

Example when it does not. 
https://github.com/ShokoAnime/Shoko-WebUI/assets/9443295/de701896-f39d-423b-8f6c-e4d15bd1a0ca

2024-01-12 10:21 UTC, harshithmohan requested changes

2024-01-12 10:21 UTC, harshithmohan commented on src/components/Input/Input.tsx
> +import { useEventCallback } from 'usehooks-ts';
Use our custom `useEventCallback` hook.
At other places too

2024-01-13 10:13 UTC, merged